public class DailyAdvice
{
    List<string> _advices = new List<string> {
    "Get up early and take advantage of the morning calm.",
    "Stretch when you wake up to wake up your muscles.",
    "Have a glass of water before breakfast.",
    "Have a healthy and balanced breakfast.",
    "Practice gratitude, think of three things you are grateful for.",
    "Plan your day before starting.",
    "Set achievable goals for the day.",
    "Take time for meditation or reflection.",
    "Exercise, even if it's a short walk.",
    "Listen to uplifting music.",
    "Read something inspiring.",
    "Smile at the people you meet.",
    "Do something kind for someone else.",
    "Limit time on social media.",
    "Dedicate time to a hobby you enjoy.",
    "Learn something new.",
    "Organize a cluttered space.",
    "Make a list of things you're proud of.",
    "Take regular breaks throughout the day.",
    "Eat a serving of fruits or vegetables.",
    "Make a call to a loved one.",
    "Practice deep breathing.",
    "Take a pause to appreciate nature.",
    "Create a playlist of happy songs.",
    "Write in a journal your thoughts and feelings.",
    "Practice self-compassion.",
    "Plan a special meal for the day.",
    "Make a list of things that make you laugh.",
    "Say 'no' to something that causes unnecessary stress.",
    "Create a playlist of motivational videos.",
    "Take a relaxing bath.",
    "Make a list of movies you'd like to watch.",
    "Practice mindfulness while eating.",
    "Make a list of books you'd like to read.",
    "Make a list of your favorite places to visit.",
    "Dedicate time to do crafts.",
    "Make a list of your dreams and aspirations.",
    "Make a list of people who inspire you.",
    "Make a donation to a cause you believe in.",
    "Do a task you've been putting off.",
    "Take a walk on a nature trail.",
    "Make a list of people you admire.",
    "Make a list of your recent achievements.",
    "Make a call to an old friend.",
    "Make a list of people who have helped you in your life.",
    "Make a list of things you'd like to learn.",
    "Make a list of your favorite places in your city.",
    "Make a list of things that make you feel relaxed.",
    "Make a list of people who have inspired you.",
    "Make a list of things that make you feel hopeful.",
    "Make a list of your happy moments.",
    "Make a list of people who make you feel motivated.",
    "Make a list of things that make you feel joyful.",
    "Make a list of your favorite foods.",
    "Make a list of your favorite inspirational quotes.",
    "Make a list of your cherished memories.",
    "Make a list of people who make you feel understood.",
    "Make a list of things that make you feel enriched.",
    "Make a list of people who make you feel valued.",
    "Make a list of things that make you feel excited.",
    "Make a list of people who make you feel balanced.",
    "Make a list of things that make you feel in harmony.",
    "Make a list of people who make you feel inspired.",
    "Make a list of things that make you feel at peace.",
    "Make a list of people who make you feel calm.",
    "Make a list of things that make you feel excited.",
    "Make a list of people who make you feel in harmony.",
    "Make a list of things that make you feel inspired.",
    "Make a list of people who make you feel grateful.",
    "Make a list of things that make you feel optimistic.",
    "Make a list of people who make you feel enriched.",
    "Make a list of things that make you feel connected.",
    "Make a list of people who make you feel energized.",
    "Make a list of things that make you feel alive.",
    "Make a list of people who make you feel happy.",
    "Make a list of things that make you feel brave.",
    "Make a list of people who make you feel accepted.",
    "Make a list of things that make you feel free.",
    "Make a list of people who make you feel supported.",
    "Make a list of things that make you feel renewed.",
    "Make a list of people who make you feel in tune.",
    "Make a list of things that make you feel in unity.",
    "Make a list of people who make you feel loving.",
    "Make a list of things that make you feel enriched.",
    "Make a list of people who make you feel valued.",
    "Make a list of things that make you feel loved."
    };

    Random randomIndex = new Random();

    public string GetRandomAdvice()
    {
        string randomAdvice = _advices[randomIndex.Next(_advices.Count)];

        return randomAdvice;
    }
}

    
